#!/bin/bash

# usage: diskmv sourcedirectory sourcedisk destinationdisk
#
# sourcedirectory is any user share directory
# sourcedisk is an array disk that contains the sourcedirectory (example: disk4 or /mnt/disk4)
# destinationdisk is an array disk to which the sourcederectory should be copied (example: disk2 or /mnt/disk2)

# The same find/rsync structure used in the unraid mover script is used to copy files and directories and then 
# delete only if the copy succeeds

if [ -d "$1" ]
then
  FULLNAME=$(readlink -e "$1")   # Handle relative path
  MERGEDIR=${FULLNAME#/mnt/*/}   # Remove any /mnt/*/ prefix
else
  MERGEDIR="$1"
fi

if [ ! -d "/mnt/user/$MERGEDIR" ]
then 
  echo "$1 is not a valid user share"
  exit 1
fi

SRCDISK=${2#/mnt/}    #Remove any leading /mnt/ prefix
SRCDISK=${SRCDISK%%/*}    #Remove any trailing path
if [ ! -d "/mnt/$SRCDISK" \
    -o "${SRCDISK:0:4}" != "disk" -a "$SRCDISK" != "cache" \
   ]
then
  echo "$2 is not a valid disk"
  exit 1
fi

DESTDISK=${3#/mnt/}    #Remove any leading /mnt/ prefix
DESTDISK=${DESTDISK%%/*}    #Remove any trailing path
if [[ ! -d "/mnt/$DESTDISK" \
     || "$DESTDISK" != disk[1-9] && "$DESTDISK" != disk[1-9][0-9] && "$DESTDISK" != "cache" \
   ]]
then
  echo "$3 is not a valid disk"
  exit 1
fi

echo "Merging /mnt/$SRCDISK/$MERGEDIR into /mnt/$DESTDISK/$MERGEDIR"
cd /mnt/$SRCDISK

find "./$MERGEDIR" -depth \
      \( \
        \( -type f ! -exec fuser -s {} \; \) \
        -o \
        \( -type d -empty \) \
      \) \
      -print \
      \( \
        -exec [ ! -f "/mnt/$DESTDISK/{}" ] \; \
        -o \
        -exec echo "Duplicate skipped: {}" \; \
        -a \
        -exec false \; \
      \) \
      -exec rsync -i -dIWRpEAXogt --numeric-ids --inplace {} /mnt/${DESTDISK}/ \; \
      -delete

echo "diskmv finished"
